apiVersion: apps/v1
kind: Deployment
metadata:
  name: name-api
  namespace: netcore
  labels:
    name: name-api
spec:
  replicas: 2
  selector:
    matchLabels:
      name: name-api
  template:
    metadata: 
     labels: 
       name: name-api
    spec:
      containers: 
      - name: name-api
        image: registry.check.com/netcore/name-api
        ports:
        - containerPort: 80
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 100m
            memory: 256Mi

---

apiVersion: v1
kind: Service
metadata:
  name: name-api
  namespace: netcore
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: name-api
      
